# Task 3: Model Building

In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [2]:
updated_df = pd.read_csv('tel_churn.csv')

In [3]:
updated_df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,TotalCharges_998.1,TotalCharges_999.45,TotalCharges_999.8,TotalCharges_999.9,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,0,1,0,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
1,1,0,56.95,0,0,1,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,2,0,53.85,1,0,1,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
3,3,0,42.30,0,0,1,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,4,0,70.70,1,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0

In [4]:
updated_df.drop(columns='Unnamed: 0',inplace=True)

In [5]:
x = updated_df.drop(columns = 'Churn')

In [6]:
x.head()

,SeniorCitizen,MonthlyCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,...,TotalCharges_998.1,TotalCharges_999.45,TotalCharges_999.8,TotalCharges_999.9,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,1,0,0,1,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
1,0,56.95,0,1,1,0,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
2,0,53.85,0,1,1,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
3,0,42.30,0,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,0,70.70,1,0,1,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0

In [7]:
y = updated_df['Churn']

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [9]:
md = DecisionTreeClassifier()
md.fit(x_train,y_train)

DecisionTreeClassifier()

In [10]:
y_pred = md.predict(x_test)

In [12]:
print(classification_report(y_test,y_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1036
           1       0.59      0.50      0.54       373

    accuracy                           0.78      1409
   macro avg       0.71      0.69      0.69      1409
weighted avg       0.77      0.78      0.77      1409

In [13]:
from imblearn.combine import SMOTEENN
from sklearn.datasets import make_classification

In [14]:
sm = SMOTEENN(random_state=42)
x_resampled, y_resampled = sm.fit_resample(x, y)

In [15]:
xr_train,xr_test,yr_train,yr_test = train_test_split(x_resampled,y_resampled,test_size = 0.2)

md2 = DecisionTreeClassifier()
md2.fit(xr_train,yr_train)

DecisionTreeClassifier()

In [16]:
yr_pred = md2.predict(xr_test)

In [17]:
print(classification_report(yr_test,yr_pred,labels =[0,1]))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       447
           1       0.95      0.97      0.96       934

    accuracy                           0.95      1381
   macro avg       0.95      0.93      0.94      1381
weighted avg       0.95      0.95      0.95      1381